### ISSUE TITLE
Make refractiveindex data parser as a different module? 

### ISSUE THREAD

**Issue by toftul** [kitchenknif/PyTMM#11]
Hi Pasha! 

This refractiveindex data base parser is very nice in PyTMM. But it is not very intuitive to find -- you have to install something about transfer matrix in order to get refractive index interface.

Based on this code, I created a separate simple module which does only one thing ~and does it well~:
https://github.com/toftul/refractiveindex

Thoughts?

**Comment by kitchenknif** [comment]
Seems like a good idea. 

I think it would make sense for you to create an issue on the main repository of refractiveindex.info 

https://github.com/polyanskiy/refractiveindex.info-database

so that that project will link to your module.

**Comment by toftul** [comment]
it is already mentioned there as a related project 🙂
